### ISSUE TITLE
incompatibility with metalsmith-watch

### ISSUE THREAD

**Issue by oupala** [hurrymaplelad/metalsmith-feed#11]
When I use the configuration detailed in #5 and with metalsmith-watch and metalsmith-serve enabled, I get the following error while launching my web site in dev mode (dev mode means _watch_ and _serve_ plugins enabled):

``` bash
user@server $ npm run dev

> project@1.3.0-dev dev
> node --harmony ./index dev

[metalsmith-watch] ✓ Live reload server started on port: 35729
\metalsmith\index.js:328
        throw err;
              ^
Error: either site_url or metadata.site.url must be configured
    at Ware.<anonymous> (\metalsmith\node_modules\metalsmith-feed\lib\metalsmith_feed.js:33:19)
    at Ware.<anonymous> (\metalsmith\node_modules\metalsmith\node_modules\ware\node_modules\wrap-fn\index.js:45:19)
    at Immediate.next (\metalsmith\node_modules\metalsmith\node_modules\ware\lib\index.js:85:20)
    at Immediate._onImmediate (\metalsmith\node_modules\metalsmith\node_modules\ware\node_modules\wrap-fn\index.js:121:18)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Is there any know incompatibility between metalsmith-feed and metalsmith-watch?

**Comment by hurrymaplelad** [comment]
@oupala thanks for reporting.  This is the first I've heard of an incompatibility.  PR welcome if you find a fix!

**Comment by oupala** [comment]
I'll be glad to send you a pull request but I have no idea on how to fix this...

I am willing to fix it, but I need help to find out the origin of the problem.

**Comment by hurrymaplelad** [comment]
Let's try to debug it!  If you remove metalsmith-watch, does your site work?

**Comment by oupala** [comment]
There was no incompatibility between broken link checker and metalsmith-watch (nor with metalsmith-serve).

I had more than one `if(isDev)` statement which had misleaded me.

Sorry for the false issue. Feel free to close it.

**Comment by varya** [comment]
@oupala What was the problem? I have the same error output.

**Comment by oupala** [comment]
Sorry @varya but I really can't remember what was the problem. One year and a half is too much for my small head...

I hope you'll find a solution in your case.
