### ISSUE TITLE
Published Date is not being generated

### ISSUE THREAD

**Issue by gastaldi** [hurrymaplelad/metalsmith-feed#13]
I am not sure if this is a metalsmith-feed issue (feel free to close it if not), but the RSS feed entries are not generating the `pubDate` element, even though I have the `publishedDate` information in my posts. 

Here is a working example: https://github.com/wildfly-swarm/wildfly-swarm.io 
Run it with `make serve` and check the rss.xml file generated

**Comment by gastaldi** [comment]
The (rather ugly) solution I found so far is to set the publishDate in the `postDescription` function, like in:
````javascript
    // RSS Feed
    .use(feed(
          {
            collection: 'posts', 
            pubDate: new Date(), 
            postDescription: function(file) {
              // Ugly hack to set publish date on RSS feed. 
              file.date = file.publishDate; 
              return file.less || file.excerpt || file.contents;
            }
          }
    ))
````

**Comment by hurrymaplelad** [comment]
@gastaldi, it's true, `file.date` is the attribute the [rss module expects](https://github.com/dylang/node-rss#itemoptions), and the attribute most Metalsmith plugins write:
- https://github.com/sanx/metalsmith-date-in-filename/
- https://github.com/fortes/metalsmith-jekyll-dates

If you'd prefer to use `publishedDate` on your posts, you'll need to map it to `date` before it gets to `rss`. The `preprocess` hook is the recommended place to do this. I'm planning to kill the
