### ISSUE TITLE
How to use the postCustomElements option

### ISSUE THREAD

**Issue by wernerglinka** [hurrymaplelad/metalsmith-feed#20]
How do I use the postCustomElements option to add an image to my rss feed?

This plugin works well, it could use a little more documentarion ;-)

**Comment by hurrymaplelad** [comment]
There's an example in the tests:
https://github.com/hurrymaplelad/metalsmith-feed/blob/master/test/metalsmith_feed.test.coffee#L72

More documentation is always welcome! 😄
