### ISSUE TITLE
Setup multiple feeds for different collections?

### ISSUE THREAD

**Issue by trst** [hurrymaplelad/metalsmith-feed#22]
Is it possible to setup more than one feed for a setup that has more than one collection?

**Comment by hurrymaplelad** [comment]
Yep! Added examples to the readme, and tests to back it up.
See https://github.com/hurrymaplelad/metalsmith-feed/commit/c058842e1206ae4d660d1749325f3110c592e002#diff-04c6e90faac2675aa89e2176d2eec7d8R56
