### ISSUE TITLE
Use a different timestamp than the default?

### ISSUE THREAD

**Issue by ben-eb** [hurrymaplelad/metalsmith-feed#3]
Thanks for the plugin, I just wondered if it would be possible to specify a callback for modifying the published date for each entry. My blog uses the `YYYY-MM-DD` format without a manual timestamp, instead [my template will pick up the file modified time](https://github.com/ben-eb/beneb.info/blob/master/templates/partials/entryBody.hbs#L10) and use that as the published date. I was wondering if that was possible to do in the feed too?

Probably would look something like this (sorry, I don't know much coffeescript):

```js
Metalsmith('example')
  .use(feed({
    date: function (item) {
      // item refers to the post / article
      return item.stats.mtime;
    }
  });
```

**Comment by hurrymaplelad** [comment]
Howdy @ben-eb!  While I'm not opposed to adding an optional date transformation function, I'm not convinced we need it.  Could you set `file.date` from `stats.mtime` earlier in the metalsmith pipeline?

I'm imagining something like:
```coffee
Metalsmith('example')
  .use (files, metalsmith, done) ->
    files.forEach (file) ->
      file.date = file.stats.mtime
    done()
  .use feed(collection: 'posts')
```

Seems pretty similar syntactically to the transformation you requested, and it'd work for any attribute.  I use [metalsmith-plugin-jekyll](https://github.com/fortes/metalsmith-jekyll-dates/blob/master/src/index.js) to do something similar, setting `file.date` from the filename.

**Comment by ben-eb** [comment]
Having thought about it a bit more, I think I probably need to keep a cache of these around somewhere, as the original timestamp (`stats.mtime`) for the post changes when it is updated. The joys of not having a database! But, I like your solution, that would probably work for at least the original published time.
