### ISSUE TITLE
no feed generated if configuration use an absolute path

### ISSUE THREAD

**Issue by oupala** [hurrymaplelad/metalsmith-feed#5]
I'm using metalsmith-feed with metalsmith.

There is no problem with the following build file :

``` js
    .use(feed({
        collection: 'recommendations',
        limit: 20,
        destination: 'rss/recommendations.xm'
    }))
```

But nothing is generated if the path of `destination` is an absolute path :

``` js
    .use(feed({
        collection: 'recommendations',
        limit: 20,
        destination: '/rss/recommendations.xm'
    }))
```

**Comment by oupala** [comment]
@hurrymaplelad Have you seen this issue?

**Comment by hurrymaplelad** [comment]
@oupala I haven't encountered it myself, good catch!  It definitely shouldn't silently do nothing...

When I try using an absolute path locally, I get an `EACCES` error, likely 'cause it's trying to write to the root of the filesystem.  Do you see your feed generated at the absolute filepath /rss/recommendations.xm?

Internally, this plugin uses the configured destination path as a key in metalsmith's `files` hash, so it's up to metalsmith how to handle it.  Given there posture as `just an abstraction for manipulating a directory of files`, seems correct to me to treat absolute paths as absolute filepaths, not absolute urls.  Perhaps the thing to do here is to be clear in the readme that the argument is a filepath?

**Comment by oupala** [comment]
I understand what you mean, `destination` is a filepath and should be treated as a filepath, absolute or not.

I don't know where to look for my generated feed using an absolute path. As I'm using windows, I don't know where `/` is.

My problem is that I don't want to repeat myself. Let me explain what I'm trying to do.

I trying to define the rss path in a global json file (see segmentio/metalsmith-metadata#13). Then I use the rssPath var in my metalsmith-feed configuration **and** in my handlebars templates. This way, I define the path only once and I get the rss feed generated at the right place. The main advantage is that I'm always consistent, I can't have my rss feed generated at one place and linked to another place (for example, when updating the path).

The problem is that:

- metalsmith-feed is waiting for a relative path to the filesystem where the file should be generated,
- while my templates are waiting for an absolute path - I mean absolute path for the generated website - so that links are still valid whenever they are used in the main template or in a sub-template.

How would you manage such mecanism? How are you doing to tell your users what is the feed url?

**Comment by oupala** [comment]
In fact, after a bit of thinking, I don't see the point of treating absolute path like absolute path. It does not make sense to generate the rss file outside the `build` directory generated by metalsmith.

Any path, absolute or not in its form, should be considered as relative to the `__dirname` of metalsmith (the `build` directory once the build process is over).

This would then make the `destination` consistent between the **file path** which is relative to the build directory of metalsmith, and the **web path** which is relative to the root directory of the webserver.

If destination equals `/rss/my-category.rss`, metalsmith would generate the file at `__dirname` + `/rss/my-category.rss` (`build/rss/my-category.rss`) and we could use the same variable in template where the link to the rss feed would be `/rss/my-category.rss` (`http://example.org/rss/my-category.rss`).

What's your opinion about my proposal?

**Comment by hurrymaplelad** [comment]
@oupala I also don't see much use for treating the destination as an absolute file path, but I do think it's important for metalsmith plugins to behave consistently.  All [other plugins](https://github.com/aymericbeaumet/metalsmith-concat/blob/master/lib/index.js#L41) I've seen treat path options as file paths, not web paths, so I think you've got a long battle to see this change through.

I think you have a lot of options for avoiding duplication.  Options include:
 - configure both the file path and the web path of the rss file in your metadata.  It's pretty easy to compute one from the other: `rssWebPath = '/' + rssFilePath` or somesuch.

 - convert the `.path` attributes of all files to absolute paths [late in the plugin flow](https://github.com/hurrymaplelad/hmlad.com/blob/master/metalsmith.coffee#L50) then read the path from the file in your templates.

**Comment by oupala** [comment]
Thank you @hurrymaplelad for this answer.

I finally ended up with the following hack:

- first, I use the following snippet to extract:

```js
// this snippet is a workaround because it is not possible to use metadata in build script
// see https://github.com/segmentio/metalsmith-metadata/issues/13
var jsonFile = fs.readFileSync('src/site.json'),
    jsonString,
    rssPath;
try {
    jsonString = JSON.parse(jsonFile);
    rssPath = jsonString['rss'];
} catch (err) {
    console.log('there has been an error parsing the json file : ' + err)
}
```

I can use `rssPath` in my feed module configuration:

```js
    .use(feed({
        collection: 'recommendations',
        limit: 20,
        destination: rssPath
    }))
```

And finally, I use a *slash-*prepended link in my footer:

```
<li><a href="/{{site.rss}}">rss</a></li>
```

where `site.rss` is a variable loaded by the **metadata** module.

**Comment by hurrymaplelad** [comment]
Closing as worked around.

**Comment by oupala** [comment]
It would be better if the issue can be fixed instead of simply adding a workaround.

I would be willing to remove the ugly workaround if the bug was fixed.
