### ISSUE TITLE
ignore excerpts and use full-text

### ISSUE THREAD

**Issue by deltamualpha** [hurrymaplelad/metalsmith-feed#6]
Are you interested in a PR that lets the user force one of `file.less or file.excerpt or file.contents`, instead of defaulting to that logic?

**Comment by deltamualpha** [comment]
Actually, what's even better is anonymous functions! Would you accept this PR if I opened it? https://github.com/deltamualpha/metalsmith-feed/commit/7c09cfc3aeaba8240dbcc5fcc630deb88dc913fe

**Comment by hurrymaplelad** [comment]
@deltamualpha sounds great!  Could even default `options.post_description` to `(file) -> file.less or file.excerpt or file.contents`

**Comment by deltamualpha** [comment]
Like this? https://github.com/deltamualpha/metalsmith-feed/commit/08c0421289d7db23a0efb3307421957724101cbe

**Comment by hurrymaplelad** [comment]
Exactly! 

Minor nitpick, all [other](https://github.com/RobinThrift/metalsmith-paginate#options) [plugins](https://github.com/segmentio/metalsmith-collections#collection-metadata) use camelCase :camel: for options, mind switching from snake_case :snake: ?
